name: 'Enhanced Task Completed Checker'
description: 'An action that checks if all tasks are completed in the pull requests.'
author: 'miguelpragosa'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'check-square'
  color: 'green'
